In [2]:
import pandas as pd

In [12]:
from tqdm import tqdm,trange

In [3]:
raw_data = pd.read_csv('./CaA_count_matrix.txt',sep='\t')

In [4]:
raw_data.head()

,gene_id,Flower_1-1,Flower_1-2,Flower_2-1,Flower_2-2,Flower_3-1,Flower_3-2,Leaf_1-1,Leaf_1-2,Leaf_2-1,...,Leaf_3-1,Leaf_4-1,Leaf_4-2,Root_1-1,Root_1-2,Root_2-1,Root_3-1,Root_3-2,Stem_1,Stem_2
0,CaA03G00795.t1,0.000000,4.675718,0.569155,0.285764,1.716129,1.152592,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.871391,0.000000,0.288512,0.000000,0.289624,0.860006,0.852294
1,CaA02G00335.t1,793.646383,1505.588170,606.080042,565.314846,1405.094480,1434.033628,290.648039,568.294289,276.784753,...,356.787464,244.224929,994.666198,871.917953,1074.447777,1376.786430,1715.637211,1353.842365,435.870226,585.188175
2,CaA08G00555.t1,755.439038,751.995046,460.613917,556.392126,197.296203,175.637536,104.458383,289.241369,23.130038,...,137.466591,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,118.970365,118.643130
3,CaA10G00138.t1,5.310135,2.410270,1.173663,2.357843,1.769983,0.000000,7.644730,3.561855,2.368247,...,4.233873,2.460045,2.992931,5.391539,3.567045,2.976966,1.185970,1.792865,3.549831,5.279612
4,CaA13G00181.t1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.333296,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.531322,0.000000,0.000000,0.000000

In [5]:
data_round = raw_data.round()

In [6]:
data_round.head()

,gene_id,Flower_1-1,Flower_1-2,Flower_2-1,Flower_2-2,Flower_3-1,Flower_3-2,Leaf_1-1,Leaf_1-2,Leaf_2-1,...,Leaf_3-1,Leaf_4-1,Leaf_4-2,Root_1-1,Root_1-2,Root_2-1,Root_3-1,Root_3-2,Stem_1,Stem_2
0,CaA03G00795.t1,0.0,5.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
1,CaA02G00335.t1,794.0,1506.0,606.0,565.0,1405.0,1434.0,291.0,568.0,277.0,...,357.0,244.0,995.0,872.0,1074.0,1377.0,1716.0,1354.0,436.0,585.0
2,CaA08G00555.t1,755.0,752.0,461.0,556.0,197.0,176.0,104.0,289.0,23.0,...,137.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,119.0,119.0
3,CaA10G00138.t1,5.0,2.0,1.0,2.0,2.0,0.0,8.0,4.0,2.0,...,4.0,2.0,3.0,5.0,4.0,3.0,1.0,2.0,4.0,5.0
4,CaA13G00181.t1,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0

In [7]:
for i in trange(1,raw_data.shape[1]):
    raw_data.iloc[:,i]=raw_data.iloc[:,i].astype('int64') #按列循环，因为列数少

In [8]:
raw_data.head()

,gene_id,Flower_1-1,Flower_1-2,Flower_2-1,Flower_2-2,Flower_3-1,Flower_3-2,Leaf_1-1,Leaf_1-2,Leaf_2-1,...,Leaf_3-1,Leaf_4-1,Leaf_4-2,Root_1-1,Root_1-2,Root_2-1,Root_3-1,Root_3-2,Stem_1,Stem_2
0,CaA03G00795.t1,0,4,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CaA02G00335.t1,793,1505,606,565,1405,1434,290,568,276,...,356,244,994,871,1074,1376,1715,1353,435,585
2,CaA08G00555.t1,755,751,460,556,197,175,104,289,23,...,137,0,0,0,0,0,0,0,118,118
3,CaA10G00138.t1,5,2,1,2,1,0,7,3,2,...,4,2,2,5,3,2,1,1,3,5
4,CaA13G00181.t1,0,0,0,0,0,0,7,0,0,...,0,0,0,0,0,0,4,0,0,0

In [13]:
data_round.to_excel('CaA_count_round.xlsx',index=0)

In [14]:
data_round.to_csv('CaA_count_round.csv',sep=',',index=0)

In [15]:
data_round.to_csv('CaA_count_round.txt',sep='\t',index=0)